import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/Navbar';
import Cursor from '@/components/Cursor';


export const metadata: Metadata = {
  title: "Deezy Cuts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        
         <Navbar/>
        <Cursor/>
        {children}
      </body>
    </html>
  );
}
